package opsDash.specialAccess;

enum SAReason
{
    MILEAGE_MANIPULATION
    , MISSING_OR_DELAYED_DOCUMENTS
    , MISSING_ITEMS
    , NRC
    , ACCIDENT_VEHICLE
    , STOLEN_CAR
    , WRONG_DESCRIPTION
    , ERRORS_OR_ADMIN_ISSUES
    , FIRST_CLAIM
    , BODY_DAMAGE
    , ENGINE_OR_TRANSMISSION_DAMAGE
    , INTERIOR_DAMAGE
    , UNDER_BODY_DAMAGE
    , REGISTRATION_ISSUE
    , PURCHASE_ISSUE
    , LATE_PU_DATE_ACTUALISATION
    , SALES_GW
    , TRANSPORT_DAMAGE
    , CAR_DELIVERY_DELAY
    , HAIL_DAMAGE
}
