package opsDash.claim;

enum ClaimStatus
{
    NEW
    , WAITING_FOR_MORE_PROOFS
    , WAITING_FOR_FIRST_PROPOSAL
    , WAITING_FOR_FIRST_FEEDBACK
    , WAITING_FOR_CAR_EXPERT_DECISION
    , WAITING_FOR_HOS_DECISION
    , WAITING_FOR_VOUCHER_ACTIVATION
    , CLOSED_FULLY_PROCESSED
}
